# create amazon-cloudwatch namespace
apiVersion: v1
kind: Namespace
metadata:
  name: {{ index .Values "aws-cloudwatch-metrics" "namespace" }}
  labels:
    name: {{ index .Values "aws-cloudwatch-metrics" "labels" }}