# create cwagent service account and role binding
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ index .Values "aws-cloudwatch-metrics" "serviceAccountname" }}
  namespace: {{ index .Values "aws-cloudwatch-metrics" "namespace" }}