# create configmap for cwagent config
apiVersion: v1
data:
  # Configuration is in Json format. No matter what configure change you make,
  # please keep the Json blob valid.
  cwagentconfig.json: |
    {
      "agent": {
        "region": "{{ index .Values "aws-cloudwatch-metrics" "region" }}"
      },
      "logs": {
        "metrics_collected": {
          "kubernetes": {
          "cluster_name": "{{ index .Values "aws-cloudwatch-metrics" "clusterName" }}",
            "metrics_collection_interval": {{ index .Values "aws-cloudwatch-metrics" "metricsInterval" }}
          }
        },
        "force_flush_interval": {{ index .Values "aws-cloudwatch-metrics" "flushInterval" }}
      }
    }
kind: ConfigMap
metadata:
  name: {{ index .Values "aws-cloudwatch-metrics" "cloudWatchConfigmap" }}
  namespace: {{ index .Values "aws-cloudwatch-metrics" "namespace" }}