# deploy cwagent as daemonset
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ index .Values "aws-cloudwatch-metrics" "daemonSet" }}
  namespace: {{  index .Values "aws-cloudwatch-metrics" "namespace" }}
spec:
  selector:
    matchLabels:
      name: {{ index .Values "aws-cloudwatch-metrics" "daemonSet" }}
  template:
    metadata:
      labels:
        name: {{ index .Values "aws-cloudwatch-metrics" "daemonSet" }}
    spec:
      containers:
        - name: {{ index .Values "aws-cloudwatch-metrics" "daemonSet" }}
          image: {{ index .Values "aws-cloudwatch-metrics" "repository" }}:{{ index .Values "aws-cloudwatch-metrics" "tag" }}
          imagePullPolicy: {{ index .Values "aws-cloudwatch-metrics" "pullPolicy" }}
          resources:
            limits:
              cpu: {{ index .Values "aws-cloudwatch-metrics" "resources" "limits" "cpu" }} 
              memory: {{ index .Values "aws-cloudwatch-metrics" "resources" "limits" "memory" }} 
            requests:
              cpu: {{ index .Values "aws-cloudwatch-metrics" "resources" "requests" "cpu" }}
              memory: {{ index .Values "aws-cloudwatch-metrics" "resources" "requests" "memory" }}
          # Please don't change below envs
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CI_VERSION
              value: "k8s/1.3.15"
          # Please don't change the mountPath
          volumeMounts:
            - name: cwagentconfig
              mountPath: /etc/cwagentconfig
            - name: rootfs
              mountPath: /rootfs
              readOnly: true
            - name: dockersock
              mountPath: /var/run/docker.sock
              readOnly: true
            - name: varlibdocker
              mountPath: /var/lib/docker
              readOnly: true
            - name: containerdsock
              mountPath: /run/containerd/containerd.sock
              readOnly: true
            - name: sys
              mountPath: /sys
              readOnly: true
            - name: devdisk
              mountPath: /dev/disk
              readOnly: true
      nodeSelector:
        kubernetes.io/os: linux
      volumes:
        - name: cwagentconfig
          configMap:
            name: cwagentconfig
        - name: rootfs
          hostPath:
            path: /
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
        - name: varlibdocker
          hostPath:
            path: /var/lib/docker
        - name: containerdsock
          hostPath:
            path: /run/containerd/containerd.sock
        - name: sys
          hostPath:
            path: /sys
        - name: devdisk
          hostPath:
            path: /dev/disk/
      terminationGracePeriodSeconds: {{ index .Values "aws-cloudwatch-metrics" "terminationGracePeriodSeconds" }}
      serviceAccountName: {{ index .Values "aws-cloudwatch-metrics" "serviceAccountname" }}