kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ index .Values "aws-cloudwatch-metrics" "roleBinding" }}
subjects:
  - kind: ServiceAccount
    name: {{ index .Values "aws-cloudwatch-metrics" "serviceAccountname" }}
    namespace: {{ index .Values "aws-cloudwatch-metrics" "namespace" }}
roleRef:
  kind: ClusterRole
  name: {{ index .Values "aws-cloudwatch-metrics" "clusterRole" }}
  apiGroup: rbac.authorization.k8s.io